Fixups near unquoted variables
Using the following command to find unquoted variables (and ignoring
more than a a few false positives),

    grep -Prn --exclude-dir=.git '(?<!["=]|\[\[ |\[\[ -[zn] )\$(?!{?#|\(|\? )'

one is lead to find a few cleanups that are something other than "add
double-quotes".  That's what these are.  We'll leave dumb adding of
double-quotes for another commit.

Most of these are still fixing quoting issues, just with a better fix.

 - parse_pkgbuilds.sh: Avoid having to escape quotes in `eval` strings
   by simplifying {backup,restore}_package_variables by using use
   `declare -p` to store all of the package variables together
 - sourceballs: Avoid using ary=($string) to do field separation by
   using `read`
 - sourceballs: Replace `[[ -z ${ary[*]} ]]` with `(( ${#ary[@]} == 0 ))`
 - db-functions: Replace
	echo ${@%\.*} | sed "s/ /\n/g"
   with
	printf '%s\n' "${@%\.*}"
 - db-functions: Replace for/echo loop over an array with `printf '%s\n'`
 - db-functions: set_repo_permissions: Line up error messages, quote "$group"
 - db-functions: Use `${ary[*]}` instead of `${ary[@]}` within strings
 - db-move: Replace `$(echo ${array[@]})` with `${array[*]}`
 - testing2x: Use `"$@"` instead of `$*` when looping over an array

Then there are a couple of changes that land on the same line as
quoting issue, but aren't really quoting related.

 - db-functions: Replace
	[[ -n "$(... | sort | uniq -D)" ]]
   with
	! ... | awk 'a[$0]++>1{exit 1}'
 - testing2x: Yes, quote arrays when looping over them, but also
   remove extra whitespace from the line

v2:
 - sourceballs: fix the intentional string separation
 - sourceballs: use ${#ary[@]} when appropriate
 - db-update: quote the "-" in a glob, for style reasons
 - db-functions: replace sort|uniq with awk
v3:
 - split in to a separate commit from the dumb-double-quote commit
 - combine the sort|uniq -> awk replacement commit with this one
 - use `declare -p` to simplify {backup,restore}_package_variables
 - use (( )) instead of [[ ]] when checking if an array is empty

diff --git a/db-functions b/db-functions
--- a/db-functions
+++ b/db-functions
@@ -282,7 +282,7 @@ getpkgfile() {
 
 getpkgfiles() {
 	local f files
-	if [[ ! -z "$(echo ${@%\.*} | sed "s/ /\n/g" | sort | uniq -D)" ]]; then
+	if ! printf '%s\n' "${@%\.*}" | awk 'a[$0]++>1{exit 1}'; then
 		error 'Duplicate packages found!'
 		exit 1
 	fi
@@ -361,9 +361,7 @@ check_splitpkgs() {
 		fi
 
 		local svnnames=($(. "${WORKDIR}/pkgbuilds/${repo}-${_pkgarch}/${_pkgbase}"; echo ${pkgname[@]}))
-		for svnname in ${svnnames[@]}; do
-			echo "${svnname}" >> "${repo}/${_pkgarch}/${_pkgbase}/svn"
-		done
+		printf '%s\n' "${svnnames[@]}" >> "${repo}/${_pkgarch}/${_pkgbase}/svn"
 	done
 	popd >/dev/null
 
@@ -433,9 +431,9 @@ set_repo_permission() {
 
 	if [[ -w ${dbfile} ]]; then
 		local group=$(/usr/bin/stat --printf='%G' "$(dirname "${dbfile}")")
-		chgrp $group "${dbfile}" || error "Could not change group of %s to %s" "$dbfile" "$group"
+		chgrp "$group" "${dbfile}"    || error "Could not change group of %s to %s" "$dbfile" "$group"
 		chgrp $group "${filesfile}" || error "Could not change group of %s to %s" "$filesfile" "$group"
-		chmod g+w "${dbfile}" || error "Could not set write permission for group %s to %s" "$group" "$dbfile"
+		chmod g+w "${dbfile}"    || error "Could not set write permission for group %s to %s" "$group" "$dbfile"
 		chmod g+w "${filesfile}" || error "Could not set write permission for group %s to %s" "$group" "$filesfile"
 	else
 		error "You don't have permission to change %s" "$dbfile"
@@ -450,7 +448,7 @@ arch_repo_add() {
 	# package files might be relative to repo dir
 	pushd "${FTP_BASE}/${repo}/os/${arch}" >/dev/null
 	/usr/bin/repo-add -q "${repo}${DBEXT}" ${pkgs[@]} \
-		|| error "repo-add ${repo}${DBEXT} ${pkgs[@]}"
+		|| error "repo-add ${repo}${DBEXT} ${pkgs[*]}"
 	popd >/dev/null
 	set_repo_permission "${repo}" "${arch}"
 
@@ -468,7 +466,7 @@ arch_repo_remove() {
 		return 1
 	fi
 	/usr/bin/repo-remove -q "${dbfile}" ${pkgs[@]} \
-		|| error "repo-remove ${dbfile} ${pkgs[@]}"
+		|| error "repo-remove ${dbfile} ${pkgs[*]}"
 	set_repo_permission "${repo}" "${arch}"
 
 	REPO_MODIFIED=1
