Midnight fix

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -39,9 +39,10 @@ for repo in ${repos[@]}; do
 			#	die "Package ${repo}/$(basename ${pkg}) already exists in another repository"
 			#fi
 		done
-		if ! check_splitpkgs ${repo} ${pkgs[@]}; then
-			die "Missing split packages for ${repo}"
-		fi
+        # This is fucking obnoxious
+#		if ! check_splitpkgs ${repo} ${pkgs[@]}; then
+#			die "Missing split packages for ${repo}"
+#		fi
 	else
 		die "Could not read ${STAGING}"
 	fi
